import Head from "next/head";
import Header from "@/components/Header";
import { Avatar, Box, Button, Tooltip, Typography } from '@mui/material';
import { auth, provider } from '../firebaseConfig';
import { signInWithPopup } from 'firebase/auth';
import { useState } from 'react';



export default function Home() {

  const [user, setUser] = useState(null);


  const handleGoogleSignIn = async () => {
    try {
      const result = await signInWithPopup(auth, provider);
      setUser(result.user);
    } catch (error) {
      if (error.code === 'auth/popup-closed-by-user') {
        alert('Popup was closed before completing sign-in.');
      } else {
        console.error('Error during sign-in:', error);
        alert('Login failed. Please try again.');
      }
    }
  };

  return (
    <>
      <Head>
        <title>Next Expo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      
      <Box sx={{
        display: 'flex',
        flexDirection:'column',
        gap:'10',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '100vh',
      }}>
     { user?(
       <>
       <Avatar src={user.photoURL} sx={{ width: 80, height: 80, mb: 2 }} />
       <Typography variant="h6">Welcome, {user.displayName}!</Typography>
       <Typography variant="body2">{user.email}</Typography>
       <Button variant="outlined" sx={{ mt: 2 }} onClick={() => {
         auth.signOut();
         setUser(null);
       }}>
         Logout
       </Button>
     </>
     ):(
      <Tooltip  title="Click to sign in with Google" arrow>
      <Button variant="contained" sx={{ backgroundColor: '#00BFFF',transition: 'transform 0.3s ease','&:hover': {transform: 'scale(1.05)',}, }} 
        onClick={handleGoogleSignIn}>
        Sign in with Google
      </Button>
      </Tooltip>
      )}
    </Box>
    </>
  );
}
